
services:
  # Your Node.js application
  app:
    build: .
    env_file: .env  # ← Load variables from .env
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - .:/usr/src/index  # for development (optional)
      - /usr/src/index/node_modules  # keep container's node_modules

  # PostgreSQL database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: